apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherforecast-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weatherforecast
  template:
    metadata:
      labels:
        app: weatherforecast
    spec:
      containers:
      - name: weatherforecast
        image: fong62/weatherforecast:${BUILD_ID}
        ports:
        - containerPort: 8080
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"