apiVersion: v1
kind: Service
metadata:
  name: weatherforecast-service
spec:
  selector:
    app: weatherforecast
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30081
  type: NodePort